apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: py3kgt2v419-svc 
  janus-idp.io/tekton: py3kgt2v419-svc
  backstage.io/kubernetes-id: py3kgt2v419-svc
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: py3kgt2v419-svc
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml