apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: py3kgt2v419-svc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: py3kgt2v419-svc 
  name: py3kgt2v419-svc
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: py3kgt2v419-svc 
